openapi: "3.1"
info:
  version: "0.1.1" # TODO: automatically replace this with the build tag...
  title: "Greypot Studio"
  summary: "Greypot Studio is an API for Report Design and Generation"
  description: "Greypot Studio is an API for Report Design and Generation"
  termsOfService: "https://github.com/nndi-oss/greypot"
  contact:
    name: "NNDI"
    url: "https://nndi.cloud/"
    email: "hello@nndi.cloud"

servers:
  - url: "https://greypot-studio.fly.dev"
    description: "Greypot Studio on Fly.io"

  - url: "https://greypot-studio.nndi.cloud/"
    description: "Greypot Studio Cloud service by NNDI"

externalDocs:

paths:
  "/_studio/generate/pdf/{id}":
    post:
      

  /_studio/reports/list:
    get:

  /_studio/reports/export/:
    get:
  /_studio/reports/preview/:
    get:
  /_studio/reports/render/:
    get:
  /_studio/reports/export/html/:
    post:
  /_studio/reports/export/pdf/:
    post:
  /_studio/reports/export/png/:
    post:
    
  /_studio/reports/export/bulk/html/:
    post:
  /_studio/reports/export/bulk/pdf/:
    post:
  /_studio/reports/export/bulk/png/:
    post:
  
components:
  schemas:
    GenerateRequest:
      type: object
      properties:
        Name:
          type: string
          required: true
        Template:
          type: string
          description: HTML Content of the template
          required: true
        Data:
          type: string
          description: JSON encoded data for the template
          required: true
    ExportResponse:
      type: object
      properties:
        reportId:
          type: string
        data: 
          type: string
          description: Base64 encoded data file of the generated report
        type:
          type: string
          description: the type of report, typically "pdf"

    BulkExportEntry:
      type: object
      properties:
        ID   string `json:"_id"`
        Data any    `json:"data"`

    BulkExportRequest:
      type: object
      properties:
        ID      string            `json:"_id"`
        Entries []BulkExportEntry `json:"entries"`

    BulkExportResponse:
      properties:
        ID       string           `json:"_id"`
        ReportID string           `json:"reportId"`
        Reports  []ExportResponse `json:"reports"`
  responses:
    