openapi: "3.1.0"
info:
  version: "0.1.1" # TODO: automatically replace this with the build tag...
  title: "Greypot Studio"
  summary: "Greypot Studio is an API for Report Design and Generation"
  description: "Greypot Studio is an API for Report Design and Generation"
  termsOfService: "https://github.com/nndi-oss/greypot"
  contact:
    name: "NNDI"
    url: "https://nndi.cloud/"
    email: "hello@nndi.cloud"

servers:
  - url: "https://greypot-studio.fly.dev"
    description: "Greypot Studio on Fly.io"

paths:
  /_studio/generate/pdf/{id}:
    post:
      responses:
        default:
          description: Default response
          application/json:
            $ref: '#/components/schemas/ErrorResponse'
  
components:
  schemas:
    GenerateRequest:
      type: object
      properties:
        Name:
          type: string
          required: true
        Template:
          type: string
          description: HTML Content of the template
          required: true
        Data:
          type: string
          description: JSON encoded data for the template
          required: true
    ExportResponse:
      type: object
      properties:
        reportId:
          type: string
        data: 
          type: string
          description: Base64 encoded data file of the generated report
        type:
          type: string
          description: the type of report, typically "pdf"
    ErrorResponse:
      type: object
      properties:
        message: 
          type: string

    